### ISSUE TITLE
Remove duplicate entries in user DataFrame and Improve Algo

### ISSUE THREAD

**Issue by Shravsssss** [Shravsssss/MovieRecommender#11]
- If a user has selected the same movie multiple times, the algorithm should first remove these duplicate selections using deduplication, keeping only one instance of each movie. The recommendation algorithm should then run on this cleaned, unique set of movies to generate suggestions. 

- Current genre processing involves row iteration, which is inefficient. Improve performance by using pandas get_dummies() for genre encoding.

**Comment by Chirag-Hegde** [comment]
Closing this issue with the solution in this commit b6ce8583fd34d55067fc794cf6285e2b967f2c25.
